### ISSUE TITLE
Complexidade excessiva

### ISSUE THREAD

**Issue by alessandroliafook** [alessandroliafook/projetoSi#2]
Problema: O bando de dados de armazenamento utilizado insere a necessidade de instalação de sistemas auxiliares, aumentando ao complexidade do sistema sem nenhum ganho aparente.

Solução: Remoção do uso do banco de dados do postgres para o bando de dados default do springboot.

**Comment by caiovidaln** [comment]
Mas o banco default não salva apenas em memória não?
